package com.example.client;

import com.example.client.gen.Person;
import com.example.client.gen.PersonService;
import com.example.client.gen.ResultDTO;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * Created by akila on 12/11/16.
 */
public class SOAPPublisherClient {

    public static void main(String[] args) throws MalformedURLException {

        //all the codes in com.example.client.ws.service.ws.gen package is generated by wsimport as bellow command
        //then toString method is added in Person class in there
        //wsimport -keep -p com.example.client http://localhost:8888/ws/person?wsdl


        URL wsdlURL = new URL("http://localhost:8888/ws/person?wsdl");
        //check above URL in browser, you should see WSDL file

        //creating QName using targetNamespace and name
        QName qname = new QName("http://impl.service.server.example.com/", "PersonServiceImplService");

        Service service = Service.create(wsdlURL, qname);

        //We need to pass interface and model beans to client
        PersonService ps = service.getPort(PersonService.class);

        Person p1 = new Person(); p1.setName("Akila"); p1.setId(1); p1.setAge(27);
        Person p2 = new Person(); p2.setName("Amila"); p2.setId(2); p2.setAge(20);

        //add person
        System.out.println("Add Person Status="+ps.addPerson(p1));
        System.out.println("Add Person Status="+ps.addPerson(p2));

        //get person
        System.out.println("\ngetting person with id 1\n");
        System.out.println(ps.getPerson(1).toString());

        //get all persons
        System.out.println("\ngetting all\n");
        ResultDTO result1 = ps.getAllPersons();
        if(result1.getPersonSet() == null) {
            System.out.println("No person to load");
        } else {
            for (Person person: result1.getPersonSet()) {
                System.out.println(person.toString());
            }
        }

        //delete person
        System.out.println("Delete Person with id 2 Status="+ps.deletePerson(2));

        //get all persons
        System.out.println("\ngetting all again\n");

        ResultDTO result2 = ps.getAllPersons();
        if(result2.getPersonSet() == null) {
            System.out.println("No person to load");
        } else {
            for (Person person: result2.getPersonSet()) {
                System.out.println(person.toString());
            }
        }
    }

}